# Generated by Django 3.2.8 on 2021-11-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='Slug')),
                ('visible', models.BooleanField(verbose_name='Visible?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated on ')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
